# Pipeline configuration
pipeline:
  max_concurrent: 5          # Max concurrent document processing
  timeout_seconds: 300       # Timeout per document
  
validation:
  validate_urls: true        # Validate URLs before fetching
  validate_files: true       # Validate local files
  
limits:
  max_file_size_mb: 100      # Maximum file size
  max_pages_per_pdf: 50      # Maximum pages to process
  
cache:
  enabled: true              # Enable caching
  directory: "./cache"       # Cache directory
  ttl_days: 7               # Cache time-to-live
  compress: true            # Compress cached files
  
batch:
  enabled: true             # Enable batch keyword generation
  threshold: 10             # Min documents for batch mode
  
openai:
  vision_model: "gpt-4o"    # Model for vision parsing
  keyword_model: "gpt-4o-mini"  # Model for keywords
  max_retries: 3            # API retry attempts
  
logging:
  level: "INFO"             # Logging level
  file: "pipeline.log"      # Log file
  
monitoring:
  progress_callback: true    # Enable progress callbacks
  save_report: true         # Save final report