pipeline:
  max_concurrent: 5
  timeout_seconds: 300
validation:
  validate_urls: true
  validate_files: true
limits:
  max_file_size_mb: 100
  max_pages_per_pdf: 50
cache:
  enabled: true
  directory: ./cache
  ttl_days: 7
  compress: true
batch:
  enabled: true
  threshold: 10
openai:
  vision_model: gpt-4o
  keyword_model: gpt-4o-mini
  max_retries: 3
  embedding_model: text-embedding-3-small
  dimensions: 1536
logging:
  level: INFO
  file: pipeline.log
monitoring:
  progress_callback: true
  save_report: true
  report_file: processing_report.json
qdrant:
  path: ./qdrant_data
  collection_name: datasheets
parser:
  datasheet_prompt_path: datasheet_parsing_prompt.md
chunking:
  chunk_size: 1024
  chunk_overlap: 128
storage:
  keyword_db_path: ./keyword_index.db
  base_dir: ./storage_data
